image: docker:latest

variables:
  REGISTRY_DEV: 10.3.7.221:5000
  REGISTRY_STAGING: 10.3.7.241:5000
  CONTAINER_IMAGE_DEV: ${REGISTRY_DEV}/pipelinewatch:${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE_STAGING: ${REGISTRY_STAGING}/pipelinewatch:${CI_COMMIT_SHORT_SHA}

dev-build:
  stage: build
  tags:
    - deployement
  only:
    refs:
      - k8s-dev
  script:
    - docker login ${REGISTRY_DEV} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE_DEV} .
    - docker push ${CONTAINER_IMAGE_DEV}

dev-deploy:
  stage: deploy
  tags:
    - deployement
  only:
    refs:
      - k8s-dev
  image: dtzar/helm-kubectl
  script:
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kubernetes/dev-airflow-deployment.yaml
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kubernetes/dev-k8sjob-deployment.yaml
    - kubectl config use-context dev
    - kubectl apply -f kubernetes/dev-airflow-deployment.yaml
    - kubectl apply -f kubernetes/dev-k8sjob-deployment.yaml


staging-build:
  stage: build
  tags:
    - deployement
  only:
    refs:
      - k8s-staging
  script:
    - docker login ${REGISTRY_STAGING} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE_STAGING} .
    - docker push ${CONTAINER_IMAGE_STAGING}

staging-deploy:
  stage: deploy
  tags:
    - deployement
  only:
    refs:
      - k8s-staging
  image: dtzar/helm-kubectl
  script:
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kubernetes/staging-airflow-deployment.yaml
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kubernetes/staging-k8sjob-deployment.yaml
    - kubectl config use-context staging
    - kubectl apply -f kubernetes/staging-airflow-deployment.yaml
    - kubectl apply -f kubernetes/staging-k8sjob-deployment.yaml

