apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinewatch
  namespace: greenroom
  labels:
    app: pipelinewatch
    env: charite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelinewatch
      env: charite
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: pipelinewatch
        env: charite
    spec:
      securityContext:
        runAsUser: 144171
        runAsGroup: 100100
        fsGroup: 100100
      serviceAccountName: consumer-serviceaccount
      containers:
        - name: pipelinewatch
          image: 10.32.42.225:5000/pipelinewatch:<VERSION>
          ports:
            - containerPort: 6063
          env:
          - name: env
            value: "charite"
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
          - name: nfsvol
            mountPath: /data/vre-storage
      nodeSelector:
        namespace: greenroom
      volumes:
      - name: nfsvol
        persistentVolumeClaim:
          claimName: greenroom-storage
---
apiVersion: v1
kind: Service
metadata:
  name: pipelinewatch
  namespace: greenroom
  labels:
    app: pipelinewatch
    env: charite
spec:
  ports:
  - name: http
    port: 6063
    targetPort: 6063
    nodeport:
  selector:
    app: pipelinewatch
    env: charite
  type: ClusterIP
