apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinewatch-k8s-job
  namespace: greenroom
  labels:
    app: pipelinewatch-k8s-job
    env: charite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelinewatch-k8s-job
      env: charite
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: pipelinewatch-k8s-job
        env: charite
    spec:
      serviceAccountName: consumer-serviceaccount
      containers:
        - name: pipelinewatch-k8s-job
          image: s-hdp-vre-v007.charite.de/pipelinewatch:<VERSION>
          ports:
            - containerPort: 6063
          env:
          - name: env
            value: "charite"
          - name: CONFIG_CENTER_ENABLED
            value: "true"
          - name: CONFIG_CENTER_BASE_URL
            value: "http://common.utility:5062/"
          command: ["/home/deploy/worker_k8s_job_watch.py"]
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
          - name: nfsvol
            mountPath: /data/vre-storage
          - name: nfsvol-vre-data
            mountPath: /vre-data
      nodeSelector:
        namespace: greenroom
      volumes:
      - name: nfsvol
        persistentVolumeClaim:
          claimName: greenroom-storage
      - name: nfsvol-vre-data
        nfs:
          server: bihnas2.charite.de
          path: /AG-Ritter-VRE/VRE-namespace/vre-vre-data-pvc-ab20736f-3a07-4f3e-bfc9-5c804e6a34d4/
#        persistentVolumeClaim:
#          claimName: greenroom-vre-storage
---
apiVersion: v1
kind: Service
metadata:
  name: pipelinewatch-k8s-job
  namespace: greenroom
  labels:
    app: pipelinewatch-k8s-job
    env: charite
spec:
  ports:
  - name: http
    port: 6063
    targetPort: 6063
    nodeport:
  selector:
    app: pipelinewatch-k8s-job
    env: charite
  type: ClusterIP
